---
title: "CMS Open Payments"
author: "Benjamin Chan (chanb@ohsu.edu)"
output:
  html_document:
    keep_md: yes
    toc: yes
---

**Play around with the CMS [Open Payments](http://www.cms.gov/OpenPayments) data.**

`r Sys.Date()`

`r R.Version()$version.string`


Run the script to read the data.
Hide the code and the output since it's under version control on [GitHub](https://github.com/benjamin-chan/OpenPayments).
Also, source a function library.

```{r, results="hide"}
setwd("~", "GitHub Repositories", "OpenPayments")
source("library.r")
source("getData.r")
```


Map at the state level.

```{r mapStates, fig.width=10}
DAgg <- D[,
          list(value = sum(Total_Amount_of_Payment_USDollars) / 1E6,
               region = Recipient_State),
          list(Recipient_State)]
require(choroplethr)
choroplethr(DAgg, 
            lod="state", 
            title="General + Research Payments")
```


Map at the zip code level.

```{r mapZipcodes, fig.width=10}
require(choroplethr)
choroplethr(DAgg, 
            lod="zip", 
            title="General + Research Payments")
```

```{r}
# data(zips)
# ggmap(get_map(maptype = 'toner', zoom = 4), extent = 'device') +
#   geom_polygon(aes(x = lon, y = lat, group = plotOrder),
#                data = zips, colour = NA, fill = 'red', alpha = .2) +
#   geom_path(aes(x = lon, y = lat, group = plotOrder),
#             data = zips, colour = 'white', alpha = .4, size = .4)

DAgg <- D[!is.na(Recipient_Zip_Code),
          list(value = sum(Total_Amount_of_Payment_USDollars) / 1E6,
               region = Recipient_Zip_Code),
          list(Recipient_Zip_Code)]
require(ggmap)
ggmap(get_map(maptype="toner", zoom=4), extent="panel") +
  geom_polygon(zipMap)
```
